spring.application.name=Authentication
server.port=8081

spring.datasource.url=jdbc:postgresql://db.jhpcikkpwejehmoantvb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=password_zuno2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secretKey=jasdkfu43y57et8ewjirfg5ruhf84hj5x8zrh49ehfuir894uet8gijfierfi

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danish15012006@gmail.com
spring.mail.password=wvmk glpx hshz zvje
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=danish15012006@gmail.com

eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1
eureka.instance.non-secure-port=8081
eureka.instance.instance-id=auth-service

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1