spring.application.name=ApiGateway
server.port=8083

spring.cloud.gateway.routes[0].id=ACCOUNTMANAGEMENT
spring.cloud.gateway.routes[0].uri=lb://ACCOUNTMANAGEMENT
spring.cloud.gateway.routes[0].predicates[0]=path= /create/**