spring.application.name=Transaction
server.port=8083

spring.datasource.url=jdbc:postgresql://db.oyyxtrwkmmzwbfsrtsgu.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=zunopassword2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/

transaction.daily-limit=100000
transaction.neft-min=1
transaction.rtgs-min=200000
transaction.imps-max=500000

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1
eureka.instance.non-secure-port=8083
eureka.instance.instance-id=transaction-service

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
